version: '3'

services:
  api:
    build: './MasterDataAPI'
    ports:
      - "38081:80"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    volumes:
      - ~/docker/data/masterdata:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=sb"
      - "MYSQL_DATABASE=MasterData"
      - "MYSQL_USER=reader"
      - "MYSQL_PASSWORD=reader"
    ports:
      - "3306:3306"
