version: '3'

services:
  api:
    image: shribee/api:latest
    ports:
      - "38081:80"
    depends_on:
      - mysql
    restart: on-failure
    environment:
      - DATABASE_URL=mysql+pymysql://root:sb@mysql/MasterData
  mysql:
    image: shribee/db:latest    
    ports:
      - "38080:3306"
