"""empty message

Revision ID: 37cbeca7bbdd
Revises: 
Create Date: 2019-11-15 11:37:23.172857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37cbeca7bbdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'BloodPressure', ['date'])
    op.create_unique_constraint(None, 'Weight', ['date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Weight', type_='unique')
    op.drop_constraint(None, 'BloodPressure', type_='unique')
    # ### end Alembic commands ###
